channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - opencv
  - pyyaml
  - pytorch
  - pip:
      - ast
      - jsonlib-python3
