seed: 719
model_arch: 'tf_efficientnet_b4_ns'
img_size: 512
epochs: 10
train_bs: 4
valid_bs: 4
T_0: 10
lr: 1e-4
min_lr: 1e-6
weight_decay: 1e-6
num_workers: 1
accum_iter: 2
verbose_step: 1
device: 'cpu'
label_cols: ['back', 'front', 'left', 'right', 'up']
species: 'zebra_grevys'
threshold: 0.5

